[/Script/Engine.Engine]
GameInstanceClass=/Script/Sailing.SailingGameInstance

[/Script/EngineSettings.GameMapsSettings]
GlobalDefaultGameMode=/Script/Sailing.ASailingGameMode
EditorStartupMap=/Game/Maps/MainOcean.MainOcean
; Sett til MainMenu.MainMenu når MainMenu-kartet er opprettet (tomt nivå, GameMode Override = MainMenuGameMode)
GameDefaultMap=/Game/Maps/MainOcean.MainOcean

[/Script/Engine.RendererSettings]
r.DefaultFeature.AntiAliasing=2

[/Script/AndroidFileServerEditor.AndroidFileServerRuntimeSettings]
bEnablePlugin=True
bAllowNetworkConnection=True
SecurityToken=4B49261B3347F713FA8606BA3B8532ED
bIncludeInShipping=False
bAllowExternalStartInShipping=False
bCompileAFSProject=False
bUseCompression=False
bLogFiles=False
bReportStats=False
ConnectionType=USBOnly
bUseManualIPAddress=False
ManualIPAddress=

[/Script/PythonScriptPlugin.PythonScriptPluginSettings]
bRemoteExecution=True

